laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
    Route::group(['middleware'=>'guest'], function() {
        Route::get('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/store', [AuthController::class, 'store'])->name('store');
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('auth');
    });

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout')
    ->middleware('auth');
});

Route::group(['as'=>'customer.'], function() {
    Route::get('/home', [CustomerController::class, 'home'])->name('home');
    Route::get('/product', [CustomerController::class, 'product'])->name('product');
    Route::get('/about_us', [CustomerController::class, 'about_us'])->name('about_us');
    Route::get('/share_info', [CustomerController::class, 'share_info'])->name('share_info');
});

Route::group(['prefix'=>'admin', 'as'=>'admin.', 'middleware'=>'auth'], function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
        Route::get('/', [AdminController::class, 'user_index'])->name('index');
        Route::get('/create', [AdminController::class, 'user_create'])->name('create');
        Route::post('/store', [AdminController::class, 'user_store'])->name('store');
        Route::get('/{user}/edit', [AdminController::class, 'user_edit'])->name('edit');
        Route::put('/{user}/update', [AdminController::class, 'user_update'])->name('update');
        Route::delete('/{user}', [AdminController::class, 'user_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'tanaman', 'as'=>'tanaman.'], function() {
        Route::get('/', [AdminController::class, 'tanaman_index'])->name('index');
        Route::get('/create', [AdminController::class, 'tanaman_create'])->name('create');
        Route::post('/store', [AdminController::class, 'tanaman_store'])->name('store');
        Route::get('/{tanaman}/edit', [AdminController::class, 'tanaman_edit'])->name('edit');
        Route::put('/{tanaman}/update', [AdminController::class, 'tanaman_update'])->name('update');
        Route::delete('/{tanaman}', [AdminController::class, 'tanaman_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'hama', 'as'=>'hama.'], function() {
        Route::get('/', [AdminController::class, 'hama_index'])->name('index');
        Route::get('/create', [AdminController::class, 'hama_create'])->name('create');
        Route::post('/store', [AdminController::class, 'hama_store'])->name('store');
        Route::get('/{hama}/edit', [AdminController::class, 'hama_edit'])->name('edit');
        Route::put('/{hama}/update', [AdminController::class, 'hama_update'])->name('update');
        Route::delete('/{hama}', [AdminController::class, 'hama_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'product', 'as'=>'product.'], function() {
        Route::get('/', [AdminController::class, 'product_index'])->name('index');
        Route::get('/create', [AdminController::class, 'product_create'])->name('create');
        Route::post('/store', [AdminController::class, 'product_store'])->name('store');
        Route::get('/{product}/edit', [AdminController::class, 'product_edit'])->name('edit');
        Route::put('/{product}/update', [AdminController::class, 'product_update'])->name('update');
        Route::delete('/{product}', [AdminController::class, 'product_destroy'])->name('destroy');
    });
});

Route::get('index', [AdminLTEController::class, 'index'])->name('index');

Route::group(['prefix'=>'page', 'as'=>'page.'], function() {
    Route::get('/kutu_putih', [CustomerController::class, 'kutu_putih'])->name('kutu_putih');
    Route::get('/ulat_bulu', [CustomerController::class, 'ulat_bulu'])->name('ulat_bulu');
    Route::get('/wareng_coklat', [CustomerController::class, 'wareng_coklat'])->name('wareng_coklat');
    Route::get('/fungus_gnats', [CustomerController::class, 'fungus_gnats'])->name('fungus_gnats');
    Route::get('/simbar_menjangan', [CustomerController::class, 'simbar_menjangan'])->name('simbar_menjangan');
    Route::get('/lili_paris', [CustomerController::class, 'lili_paris'])->name('lili_paris');
    Route::get('/janda_bolong', [CustomerController::class, 'janda_bolong'])->name('janda_bolong');
    Route::get('/kebo_karet', [CustomerController::class, 'kebo_karet'])->name('kebo_karet');
    Route::get('/baygon', [CustomerController::class, 'baygon'])->name('baygon');
    Route::get('/insektisida', [CustomerController::class, 'insektisida'])->name('insektisida');
    Route::get('/cklt', [CustomerController::class, 'cklt'])->name('cklt');
    Route::get('/ralat', [CustomerController::class, 'ralat'])->name('ralat');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');

    Route::get('/admin-index', function () {
        // dd(url('')."/laravel/vendor");
        return view('admin.index');
    });
});

laravel/resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>AdminLTE 2 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini fixed">
<div class="wrapper">

  @yield('header')
  <!-- Left side column. contains the logo and sidebar -->
  @yield('leftbar')

  <!-- Content Wrapper. Contains page content -->
  @yield('content')
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2022 Rorojonggrang.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  @yield('rightbar')
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/raphael/raphael.min.js"></script>
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/morris.js/morris.min.js"></script>
<!-- Sparkline -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/moment/min/moment.min.js"></script>
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/dist/js/adminlte.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ url('') }}/laravel/vendor/almasaeed2010/adminlte/dist/js/demo.js"></script>
</body>
</html>

laravel/resources/views/admin/layout/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>R</b>J</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Roro</b>Jonggrang</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="user user-menu">
            <a>
              <span class="hidden-xs">{{ auth()->user()->name }}</span>
            </a>
            <!-- <ul class="dropdown-menu">
              <li class="user-header">
                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <!-- <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
          <li>
            <a href="{{ route('user.logout') }}" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="fa fa-sign-out"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

laravel/resources/views/admin/layout/leftbar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="@if($module_name == 'Dashboard') active @endif">
          <a href="{{ route('admin.index') }}">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li class="@if($module_name == 'User') active @endif">
          <a href="{{ route('admin.user.index') }}">
            <i class="fa fa-user"></i> <span>User</span>
          </a>
        </li>
        <li class="@if($module_name == 'Tanaman') active @endif">
          <a href="{{ route('admin.tanaman.index') }}">
            <i class="fa fa-tree"></i> <span>Tanaman</span>
          </a>
        </li>
        <li class="@if($module_name == 'Hama') active @endif">
          <a href="{{ route('admin.hama.index') }}">
            <i class="fa fa-plus"></i> <span>Hama</span>
          </a>
        </li>
        <li class="@if($module_name == 'Product') active @endif">
          <a href="{{ route('admin.product.index') }}">
            <i class="ion ion-bag"></i> <span>Product</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

laravel/resources/views/admin/layout/rightbar.blade.php
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>