laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
    Route::group(['middleware'=>'guest'], function() {
        Route::get('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/store', [AuthController::class, 'store'])->name('store');
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('auth');
    });

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout')
    ->middleware('auth');
});

Route::group(['as'=>'customer.'], function() {
    Route::get('/home', [CustomerController::class, 'home'])->name('home');
    Route::get('/product', [CustomerController::class, 'product'])->name('product');
    Route::get('/about_us', [CustomerController::class, 'about_us'])->name('about_us');
    Route::get('/share_info', [CustomerController::class, 'share_info'])->name('share_info');
});

Route::group(['prefix'=>'admin', 'as'=>'admin.', 'middleware'=>'auth'], function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
        Route::get('/', [AdminController::class, 'user_index'])->name('index');
        Route::get('/create', [AdminController::class, 'user_create'])->name('create');
        Route::post('/store', [AdminController::class, 'user_store'])->name('store');
        Route::get('/{user}/edit', [AdminController::class, 'user_edit'])->name('edit');
        Route::put('/{user}/update', [AdminController::class, 'user_update'])->name('update');
        Route::delete('/{user}', [AdminController::class, 'user_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'tanaman', 'as'=>'tanaman.'], function() {
        Route::get('/', [AdminController::class, 'tanaman_index'])->name('index');
        Route::get('/create', [AdminController::class, 'tanaman_create'])->name('create');
        Route::post('/store', [AdminController::class, 'tanaman_store'])->name('store');
        Route::get('/{tanaman}/edit', [AdminController::class, 'tanaman_edit'])->name('edit');
        Route::put('/{tanaman}/update', [AdminController::class, 'tanaman_update'])->name('update');
        Route::delete('/{tanaman}', [AdminController::class, 'tanaman_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'hama', 'as'=>'hama.'], function() {
        Route::get('/', [AdminController::class, 'hama_index'])->name('index');
        Route::get('/create', [AdminController::class, 'hama_create'])->name('create');
        Route::post('/store', [AdminController::class, 'hama_store'])->name('store');
        Route::get('/{hama}/edit', [AdminController::class, 'hama_edit'])->name('edit');
        Route::put('/{hama}/update', [AdminController::class, 'hama_update'])->name('update');
        Route::delete('/{hama}', [AdminController::class, 'hama_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'product', 'as'=>'product.'], function() {
        Route::get('/', [AdminController::class, 'product_index'])->name('index');
        Route::get('/create', [AdminController::class, 'product_create'])->name('create');
        Route::post('/store', [AdminController::class, 'product_store'])->name('store');
        Route::get('/{product}/edit', [AdminController::class, 'product_edit'])->name('edit');
        Route::put('/{product}/update', [AdminController::class, 'product_update'])->name('update');
        Route::delete('/{product}', [AdminController::class, 'product_destroy'])->name('destroy');
    });
});

Route::get('index', [AdminLTEController::class, 'index'])->name('index');

Route::group(['prefix'=>'page', 'as'=>'page.'], function() {
    Route::get('/kutu_putih', [CustomerController::class, 'kutu_putih'])->name('kutu_putih');
    Route::get('/ulat_bulu', [CustomerController::class, 'ulat_bulu'])->name('ulat_bulu');
    Route::get('/wareng_coklat', [CustomerController::class, 'wareng_coklat'])->name('wareng_coklat');
    Route::get('/fungus_gnats', [CustomerController::class, 'fungus_gnats'])->name('fungus_gnats');
    Route::get('/simbar_menjangan', [CustomerController::class, 'simbar_menjangan'])->name('simbar_menjangan');
    Route::get('/lili_paris', [CustomerController::class, 'lili_paris'])->name('lili_paris');
    Route::get('/janda_bolong', [CustomerController::class, 'janda_bolong'])->name('janda_bolong');
    Route::get('/kebo_karet', [CustomerController::class, 'kebo_karet'])->name('kebo_karet');
    Route::get('/baygon', [CustomerController::class, 'baygon'])->name('baygon');
    Route::get('/insektisida', [CustomerController::class, 'insektisida'])->name('insektisida');
    Route::get('/cklt', [CustomerController::class, 'cklt'])->name('cklt');
    Route::get('/ralat', [CustomerController::class, 'ralat'])->name('ralat');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');

    Route::get('/admin-index', function () {
        // dd(url('')."/laravel/vendor");
        return view('admin.index');
    });
});

laravel/resources/views/about_us.blade.php
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{{asset('assets/CSS_files/about-us.css')}}">
  <script src="{{asset('assets/JS_files/about-us.js')}}"></script>
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <!--header part start-->
  <div class="container-fluid text-white" id="change-color">
    <div class="row" id="top-containt">
      <div class="col-4 text-center">
        <a href="login-ecommerce.html"><img src="{{asset('assets/Images/roroicon.png')}}" height="120px"
            class="color logo-1 logo-sift"></a>
        <a href="login-ecommerce.html"><img src="{{asset('assets/Images/pinterest_icon.png')}}" height="70px"
            class=" color logo-2 mt-1 ml-2"></a>
      </div>
      <div class="col-8 pt-4 mt-1 text-center">
        <span class="dropdown dropdown-toggle profile" data-toggle="dropdown" style="color:black">
          <a href="#/"><img src="{{asset('assets/Images/profile-icon.png')}}" class="profile-icon color"></a>
        </span>
        <ul class="dropdown-menu mt-4 text-center" style="margin-left:-6%;border-radius:10px;">
          @if(auth()->check())
            <li class="pre-profile-1 pt-2 pb-2"><a href="#/" class="color" style="font-weight:600">Help Center </a></li>
            <li class="pre-profile-1 pt-2 pb-2"><a href="#/" class="color" style="font-weight:600">Order History</a></li>
            <li class="pre-profile-1 pt-2 pb-2"><a href="#/" class="color" style="font-weight:600">Change Password</a></li>
            <li class="pre-profile-1 pt-2 pb-2"><a href="#/" class="color" style="font-weight:600">Update Profile</a></li>
            <li class="pre-profile-1 pt-2 pb-2"><a href="{{ route('user.logout') }}" class="color" style="font-weight:600">Log Out</a></li>
          @else
            <li class="pre-profile-1 pt-2 pb-2"><a href="{{ route('user.login') }}" class="color" style="font-weight:600">Log In </a></li>
            <li class="pre-profile-1 pt-2 pb-2"><a href="{{ route('user.register') }}" class="color" style="font-weight:600">Register</a></li>
          @endif
        </ul>
        <span class="menu-1"><a href="home" class="color">home</a></span>
        <span class="menu"><a href="product" class="color">P and P</a></span>
        <span class="menu"><a href="about_us" class="color">about</a></span>
        <span class="menu"><a href="share_info" class="color">share info</a></span>
        <span class="menu-bar text-right"><a href="#/" class="color">&#9776;</a></span>
        <span class="menu-bar-1 text-right"><a href="#/" class="color">&#9776;</a></span>
        <span class="menu-bar-2 text-right"><a href="#/" class="color">&#9776;</a></span>
      </div>
    </div>
    <div class="container-fluid side-bar px-0">
      <div class="col-12 text-right bg-danger">
        <span class="close"><a href="#/" class="color">&times;</a></span>
      </div>
      <ul class="pt-5 pre-side-bar">
        <li class="pt-4" style="margin-left:-5%;"><a href="home" class="color">home</a></li>
        <li class="pt-3" style="margin-left:-5%"><a href="product" class="color">P and P</a></li>
        <li class="pt-3" style="margin-left:-5%"><a href="about_us" class="color">about</a></li>
        <li class="pt-3" style="margin-left:-5%"><a href="share_info" class="color">share info</a></li>
        <li class="pt-3" style="margin-left:-5%"><a href="#/" class="color">Update profile</a></li>
        <li class="pt-3" style="margin-left:-5%"><a href="ecommerce.html" class="color">Log Out</a><span><a href="#"
              class="color"><img src="log-in..png" class="log-in"></a></span></li>
      </ul>
    </div>
  </div>
  <!--header part end-->

  <!--middle part start-->
  <div class="container mt-5">
    <div class="row mt-5">
      <div class="col-12 mt-5 text-center">
        <span class="header">about us</span>
      </div>
    </div>

    <!--main content-->
    <div class="row mt-5">
      <div class="col-xl-6 col-lg-6 col-sm-12 text-center">
        <img src="{{asset('assets/Images/about us.jpeg')}}" class="header-part">
      </div>
      <div class="col-xl-6 col-lg-6 col-sm-12 pt-5" style="font-weight: 600;">
      Web ini menyediakan sarana edukasi mengenai tanaman hias. Mulai dari bagaimana cara merawat
      dan membasmi hama - hama yang dapat merusak tanaman.
      Web ini dibuat user friendly agar memudahkan pengguna dalam menggunakan web.
      Kami memiliki fitur utama yaitu P AND P. Kami juga merekomendasikan obat - obat untuk membasmi hama - hama bukan hanya
      hama tanaman tetapi juga hama rumah.</span>
      </div>
    </div>
    <!--main content-->

    <!--cards-->
    <div class="row mt-5 mb-5">
      <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 mt-4 mb-4">
        <div class="card">
          <div class="card-header text-center">Nora Trivetisia</div>
          <div class="card-body"><img src="{{asset('assets/Images/Images1.jpg')}}" height="200px" width="100%">
            <p class="pt-3"> Nora Trivetisia Nim 19102018 merupakan mahasiswa ITTP prodi
              Teknik Informatika sedang belajar membuat web melalui mata kuliah pemrograman web
            </p>
          </div>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 mt-4">
        <div class="card">
          <div class="card-header text-center">Tri Wulandari Utami</div>
          <div class="card-body"><img src="{{asset('assets/Images/Images2.jpg')}}" height="200px" width="100%">
            <p class="pt-3"> Tri Wulandari Utami Nim 19102276 merupakan mahasiswa ITTP prodi
              Teknik Informatika sedang belajar membuat web melalui mata kuliah pemrograman web</p>
          </div>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12  mt-4 card-3">
        <div class="card">
          <div class="card-header text-center">Nawang Anggita Winanti</div>
          <div class="card-body"><img src="{{asset('assets/Images/Images3.jpg')}}" height="200px" width="100%">
            <p class="pt-3">Nawang Anggita Winanti Nim 19102244 merupakan mahasiswa ITTP prodi
              Teknik Informatika sedang belajar membuat web melalui mata kuliah pemrograman web</p>
          </div>
        </div>
      </div>
    </div>
    <!--cards-->
  </div>
  <!--middle part end-->

  <!--footer-->
  <div class="container-fluid bg-dark text-white">
    <div class="container">
      <div class="row ">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 footer pt-5">
          <p style="font-size:20px;text-transform: uppercase;font-weight: 800;" data-aos="slide-right">Roro
            Jonggrang</p>
          <p data-aos="slide-right">Web Rorojonggrang<br>
            dibuat sejak tahun 2021.<br>
            Web tentang tanaman hias dan,<br>
            hama serta menjual produk pembasmi hama.<br></p>
        </div>
        <div class="col-xl-3 pt-5 hide-girl">
          <span style="font-size:20px;text-transform: uppercase;font-weight: 800;"
            data-aos="zoom-in-left">P and P</span><br>
          <p style="margin-top:3%" data-aos="slide-up">Tanaman Hias</p>
          <p style="margin-top:-3%" data-aos="slide-up">Jenis Hewan</p>
          <p style="margin-top:-3%" data-aos="slide-up">Pembasmi Hama</p>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-4 col-sm-12 col-12 footer  pt-5">
          <span style="font-size:20px;text-transform: uppercase;font-weight: 800;" class="text-center"
            data-aos="zoom-in-left">Social Media </span><br>
          <p style="margin-top:3%;margin-left:1%;" data-aos="fade-up">@noratrivetisia</p>
          <p style="margin-top:-3%;margin-left:1%;" data-aos="fade-up">@Triwulandari</p>
          <p style="margin-top:-3%;margin-left:1%;" data-aos="fade-up">@NawangAnggita</p>
        </div>
        <div class="col-xl-2 col-lg-4 col-md-4 col-sm-12 col-12 footer pt-5 pb-3">
          <p style="font-size:20px;text-transform: uppercase;font-weight: 800;" data-aos="slide-left">Contact
          </p>
          <p data-aos="fade-up"><i class="fa fa-home" aria-hidden="true" style="font-size:20px;"></i>&nbsp;
            Purwokerto, 53147,</p>
          <p data-aos="fade-up"><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp; rorojonggrang@gmail.com
          </p>
          <p data-aos="fade-up"><i class="fa fa-phone" aria-hidden="true"></i>&nbsp; +62 876 9875 0123</p>
        </div>
      </div>
    </div>
    <hr style="color:white;width:100%;border:1px solid">
    <div class="container mt-4 pb-4">
      <div class="row">
        <div class="col-12 col-xl-6 col-lg-6 col-md-6 col-sm-6 ">
          <p>© 2020 Copyright:<span style="font-weight:600">Rorojonggrang</span></p>
        </div>
        <div class="col-12 col-xl-6 col-lg-6 col-md-6 col-sm-6 icon-head">
          <span class="icons-2"><i class="fa fa-facebook" aria-hidden="true"></i></span>
          <span class="icons-3"><i class="fa fa-twitter" aria-hidden="true"></i></span>
          <span class="icons-1"><i class="fa fa-google-plus" aria-hidden="true"></i></span>
          <span class="icons"><i class="fa fa-instagram" aria-hidden="true"></i></span>
        </div>
      </div>
    </div>
  </div>
  <!--footer-->
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>

  <script>
    //on scroll plugin//
    AOS.init({
      once: true,
      duration: 1000,
    });
  //on scroll plugin//
  </script>
</body>

</html>

laravel/resources/views/login_form.blade.php
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{asset('assets/CSS_files/login-form.css')}}">
    <script src="{{asset('assets/JS_files/login-form.js')}}"></script>
</head>

<body style="background-image:url('{{asset('assets/Images/login-background.jpg')}}');background-size: cover;">
    <div class="container">
        <div class="container form bg-white pt-5 mt-4 mb-3">
            <!--change after click on sign up-->
            <p class="text-center login-heading hide-me">login</p>
                <div class="container hide-me">
                    <form action="{{ route('user.auth') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col mt-4 pl-5 pr-5">
                                <p class="username">username</p>
                                <div class="row mt-4">
                                    <div class="col-2 text-center pt-1 pr-0">
                                        <i class="fa fa-user-o" aria-hidden="true" id="user"></i>
                                    </div>
                                    <div class="col-10 pl-0">
                                        <input type="text" placeholder="Type your username" class='input-1' name="username">
                                    </div>
                                </div>
                                <hr class="hr-1">
                                <div class="hide"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col mt-4 pl-5 pr-5">
                                <p class="username">Password</p>
                                <div class="row mt-4">
                                    <div class="col-2 text-center pt-1 pr-0">
                                        <i class="fa fa-lock" aria-hidden="true" id="lock"></i>
                                    </div>
                                    <div class="col-10 pl-0">
                                        <input type="password" placeholder="Type your password" class="input-2" name="password">
                                    </div>
                                </div>
                                <hr class="hr-2">
                                <div class="hide-1"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col text-right pr-5">
                                <a href="#"><span class="forget-password">Forget password?</span></a>
                            </div>
                        </div>
                        <div class="row mt-4">
                            <div class="col pl-5 pr-5">
                            <a><button class="btn btn-block text-white signup-button" type="submit" name="submit">Login</button></a>
                            </div>
                        </div>
                    </form>
                    <div class="row mt-5">
                        <div class="col text-center">
                            <span style="text-transform: capitalize;font-family: Arial, Helvetica, sans-serif;font-size:15px;font-weight:600;color:rgb(148, 141, 141)">or sign up using</span>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class='col text-center'>
                            <span class="facebook-icon"><i class="fa fa-facebook" aria-hidden="true"></i></span>
                            <span class="twitter-icon"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                            <span class="google-icon"><i class="fa fa-google" aria-hidden="true"></i></span>
                        </div>
                    </div>
                    <div class="row mt-5">
                        <div class="col text-center">
                            <span style="text-transform: capitalize;font-family: Arial, Helvetica, sans-serif;font-size:15px;font-weight:600;color:rgb(148, 141, 141)">or sign up using</span>
                        </div>
                        <div class="col-12 text-center pt-3">
                            <button type="submit"><span class="sign-up">sign up</span></button>
                        </div>
                    </div>
                </div>
                <!--change it-->
                <p class="text-center login-heading show-me">sign up</p>
                <form class="" action="{{ route('user.store') }}" method="POST" autocomplete="off">
                    @csrf
                    <div class="row show-me">
                        <div class="col mt-4 pl-5 pr-5">
                            <p class="username">Name</p>
                            <div class="row mt-4">
                                <div class="col-2 text-center pt-1 pr-0">
                                    <i class="fa fa-user-o" aria-hidden="true" id="user"></i>
                                </div>
                                <div class="col-10 pl-0">
                                    <input type="text" placeholder="Type your username" name="name" id="name" required value="">
                                </div>
                            </div>
                            <hr class="hr-1">
                            <div class="first-name-hide"></div>
                        </div>
                    </div>
                    <div class="row show-me">
                        <div class="col mt-4 pl-5 pr-5">
                            <p class="username">User name</p>
                            <div class="row mt-4">
                                <div class="col-2 text-center pt-1 pr-0">
                                    <i class="fa fa-user-o" aria-hidden="true" id="user"></i>
                                </div>
                                <div class="col-10 pl-0">
                                    <input type="text" placeholder="Type your username" name="username" id="username" required value="">
                                </div>
                            </div>
                            <hr class="hr-1">
                            <div class="last-name-hide"></div>
                        </div>
                    </div>
                    <div class="row show-me">
                        <div class="col mt-4 pl-5 pr-5">
                            <p class="username">Email-id</p>
                            <div class="row mt-4">
                                <div class="col-2 text-center pt-1 pr-0">
                                    <i class="fa fa-envelope-o" aria-hidden="true" id="user"></i>
                                </div>
                                <div class="col-10 pl-0">
                                    <input type="text" placeholder="Type your username" name="email" id="email" required value="">
                                </div>
                            </div>
                            <hr class="hr-1">
                            <div class="email-hide"></div>
                        </div>
                    </div>
                    <div class="row show-me">
                        <div class="col mt-4 pl-5 pr-5">
                            <p class="username">Password</p>
                            <div class="row mt-4">
                                <div class="col-2 text-center pt-1 pr-0">
                                    <i class="fa fa-lock" aria-hidden="true" id="lock"></i>
                                </div>
                                <div class="col-10 pl-0">
                                    <input type="password" placeholder="Type your password" name="password" id="password" required value="">
                                </div>
                            </div>
                            <hr class="hr-2">
                            <div class="password-signup-hide"></div>
                        </div>
                    </div>
                    <div class="row show-me">
                        <div class="col mt-4 pl-5 pr-5">
                            <p class="username">Confirm-password</p>
                            <div class="row mt-4">
                                <div class="col-2 text-center pt-1 pr-0">
                                    <i class="fa fa-lock" aria-hidden="true" id="lock"></i>
                                </div>
                                <div class="col-10 pl-0">
                                    <input type="password" placeholder="Type your password" name="password_confirmation" id="password-confirm" required value="">
                                </div>
                            </div>
                            <hr class="hr-2">
                            <div class="confirm-password-signup-hide"></div>
                        </div>
                    </div>

                    <div class="row show-me">
                        <div class="col pl-5">
                            <a href="#"><span class="forget-password">I accept the <span style="text-transform:capitalize;color:blue">terms of use </span>&
                                    <span style="text-transform:capitalize;color:blue">privacy policy</span> </a>
                        </div>
                    </div>
                    <div class="row mt-4 show-me">
                        <div class="col pl-5 pr-5">
                            <a><button class="btn btn-block text-white signup-button" type="submit" name="submit">sign up</button></a>
                        </div>
                    </div>

                    <div class="row mt-5 show-me">
                        <div class="col text-center">
                            <span style="text-transform: capitalize;font-family: Arial, Helvetica, sans-serif;font-size:15px;font-weight:600;color:rgb(148, 141, 141)">or sign up using</span>
                        </div>
                    </div>
                    <div class="row mt-5 show-me">
                        <div class='col text-center'>
                            <span class="facebook-icon"><i class="fa fa-facebook" aria-hidden="true"></i></span>
                            <span class="twitter-icon"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                            <span class="google-icon"><i class="fa fa-google" aria-hidden="true"></i></span>
                        </div>
                    </div>
                    <div class="row mt-5 show-me">
                        <div class="col text-center">
                            <span style="text-transform: capitalize;font-family: Arial, Helvetica, sans-serif;font-size:15px;font-weight:600;color:rgb(148, 141, 141)">already have an account</span>
                        </div>
                        <div class="col-12 text-center pt-3">
                            <a href="login_form"><span class="login-page">LOGIN</span></a>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</body>

</html>

laravel/resources/views/share_info.blade.php
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{{asset('assets/CSS_files/contact-form.css')}}">
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head><body style="background-image:url('{{asset('assets/Images/login-background.jpg')}}');background-size: cover;">    "
    "
    "
        <div class="container">
            <div class="container form bg-white pt-5 mt-4 mb-3">
                <p class="text-center contact-heading">contact us</p> 
                <div class="container">
                    <div class="row pl-5 pt-3">
                        <div class="col-12 pt-3">
                            <input type="text" placeholder="name" style="width:85%;border:transparent;border-bottom:2px solid black;height:40px" class="name">
                            <div class="name-hide"></div>
                        </div>
                        <div class="col-12 pt-4">
                            <input type="text" placeholder="mobile no." style="width:85%;border:transparent;border-bottom:2px solid black;height:40px" class="mobile">
                            <div class="mobile-hide"></div>
                        </div>
                        <div class="col-12 pt-4">
                            <input type="text" placeholder="email id" style="width:85%;border:transparent;border-bottom:2px solid black;height:40px" class="email">
                            <div class="email-hide"></div>
                        </div>
                        <div class="col-12 pt-5">
                            <textarea rows="5" placeholder="message" style="width:85%" class="message"></textarea>
                            <div class="hide-message"></div>
                        </div>
                        <div class="col-12 pt-5">
                            <a href="product"><span class="btn text-white send-button" style="width:85%">send</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </body>
</htmml>