laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
    Route::group(['middleware'=>'guest'], function() {
        Route::get('/register', [AuthController::class, 'register'])->name('register');
        Route::post('/store', [AuthController::class, 'store'])->name('store');
        Route::get('/login', [AuthController::class, 'login'])->name('login');
        Route::post('/authenticate', [AuthController::class, 'authenticate'])->name('auth');
    });

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout')
    ->middleware('auth');
});

Route::group(['as'=>'customer.'], function() {
    Route::get('/home', [CustomerController::class, 'home'])->name('home');
    Route::get('/product', [CustomerController::class, 'product'])->name('product');
    Route::get('/about_us', [CustomerController::class, 'about_us'])->name('about_us');
    Route::get('/share_info', [CustomerController::class, 'share_info'])->name('share_info');
});

Route::group(['prefix'=>'admin', 'as'=>'admin.', 'middleware'=>'auth'], function() {
    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::group(['prefix'=>'user', 'as'=>'user.'], function() {
        Route::get('/', [AdminController::class, 'user_index'])->name('index');
        Route::get('/create', [AdminController::class, 'user_create'])->name('create');
        Route::post('/store', [AdminController::class, 'user_store'])->name('store');
        Route::get('/{user}/edit', [AdminController::class, 'user_edit'])->name('edit');
        Route::put('/{user}/update', [AdminController::class, 'user_update'])->name('update');
        Route::delete('/{user}', [AdminController::class, 'user_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'tanaman', 'as'=>'tanaman.'], function() {
        Route::get('/', [AdminController::class, 'tanaman_index'])->name('index');
        Route::get('/create', [AdminController::class, 'tanaman_create'])->name('create');
        Route::post('/store', [AdminController::class, 'tanaman_store'])->name('store');
        Route::get('/{tanaman}/edit', [AdminController::class, 'tanaman_edit'])->name('edit');
        Route::put('/{tanaman}/update', [AdminController::class, 'tanaman_update'])->name('update');
        Route::delete('/{tanaman}', [AdminController::class, 'tanaman_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'hama', 'as'=>'hama.'], function() {
        Route::get('/', [AdminController::class, 'hama_index'])->name('index');
        Route::get('/create', [AdminController::class, 'hama_create'])->name('create');
        Route::post('/store', [AdminController::class, 'hama_store'])->name('store');
        Route::get('/{hama}/edit', [AdminController::class, 'hama_edit'])->name('edit');
        Route::put('/{hama}/update', [AdminController::class, 'hama_update'])->name('update');
        Route::delete('/{hama}', [AdminController::class, 'hama_destroy'])->name('destroy');
    });
    Route::group(['prefix'=>'product', 'as'=>'product.'], function() {
        Route::get('/', [AdminController::class, 'product_index'])->name('index');
        Route::get('/create', [AdminController::class, 'product_create'])->name('create');
        Route::post('/store', [AdminController::class, 'product_store'])->name('store');
        Route::get('/{product}/edit', [AdminController::class, 'product_edit'])->name('edit');
        Route::put('/{product}/update', [AdminController::class, 'product_update'])->name('update');
        Route::delete('/{product}', [AdminController::class, 'product_destroy'])->name('destroy');
    });
});

Route::get('index', [AdminLTEController::class, 'index'])->name('index');

Route::group(['prefix'=>'page', 'as'=>'page.'], function() {
    Route::get('/kutu_putih', [CustomerController::class, 'kutu_putih'])->name('kutu_putih');
    Route::get('/ulat_bulu', [CustomerController::class, 'ulat_bulu'])->name('ulat_bulu');
    Route::get('/wareng_coklat', [CustomerController::class, 'wareng_coklat'])->name('wareng_coklat');
    Route::get('/fungus_gnats', [CustomerController::class, 'fungus_gnats'])->name('fungus_gnats');
    Route::get('/simbar_menjangan', [CustomerController::class, 'simbar_menjangan'])->name('simbar_menjangan');
    Route::get('/lili_paris', [CustomerController::class, 'lili_paris'])->name('lili_paris');
    Route::get('/janda_bolong', [CustomerController::class, 'janda_bolong'])->name('janda_bolong');
    Route::get('/kebo_karet', [CustomerController::class, 'kebo_karet'])->name('kebo_karet');
    Route::get('/baygon', [CustomerController::class, 'baygon'])->name('baygon');
    Route::get('/insektisida', [CustomerController::class, 'insektisida'])->name('insektisida');
    Route::get('/cklt', [CustomerController::class, 'cklt'])->name('cklt');
    Route::get('/ralat', [CustomerController::class, 'ralat'])->name('ralat');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart');

    Route::get('/admin-index', function () {
        // dd(url('')."/laravel/vendor");
        return view('admin.index');
    });
});

laravel/resources/views/admin/hama-create.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            <form>
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="jenis">Jenis</label>
                    <input type="text" class="form-control" id="jenis" placeholder="jenis">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="exampleInputFile">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/hama-edit.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            <form>
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="jenis">Jenis</label>
                    <input type="text" class="form-control" id="jenis" placeholder="jenis">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="exampleInputFile">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/hama-index.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ $module_name }}
      </h1>
      <ol class="breadcrumb">
        <li class="active">{{ $module_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"></h3>
          <a href="{{ route('admin.hama.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="box-body">
          <table class="table">
              <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Jenis</th>
                  <th>Image</th>
                  <th>Link</th>
                  <th>Action</th>
              </tr>
              <tr>
                  <td>1</td>
                  <td>Caca</td>
                  <td>caca</td>
                  <td><a href="" class="btn btn-warning">Edit</a> <a href="" class="btn btn-danger">Delete</a></td>
              </tr>
          </table>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/index.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
      </h1>
      <ol class="breadcrumb">
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{ $user_count }}</h3>

              <p>User</p>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{{ $tanaman_count }}</h3>

              <p>Tanaman</p>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{ $hama_count }}</h3>

              <p>Hama</p>
            </div>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{{ $product_count }}</h3>

              <p>Product</p>
            </div>
          </div>
        </div>
        <!-- ./col -->
      </div>
      <!-- /.row -->

    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/product-create.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            <form>
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="jenis">Jenis</label>
                    <input type="text" class="form-control" id="jenis" placeholder="jenis">
                </div>
                <div class="form-group">
                    <label for="desc">Desc</label>
                    <input type="text" class="form-control" id="desc" name ="desc"  placeholder="desc">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image">
                            <label class="custom-file-label" for="image">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="link">Link</label>
                    <input type="text" class="form-control" id="link" name ="link"  placeholder="link">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/product-edit.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            <form>
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name4" name ="name" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="price">Price</label>
                    <input type="password" class="form-control" id="exampleInputPassword4" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="desc">Description</label>
                    <input type="text" class="form-control" id="desc" placeholder="Password">
                </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/product-index.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ $module_name }}
      </h1>
      <ol class="breadcrumb">
        <li class="active">{{ $module_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"></h3>
          <a href="{{ route('admin.product.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="box-body">
          <table class="table">
              <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Desc</th>
                  <th>Action</th>
              </tr>
              <tr>
                  <td>1</td>
                  <td>Caca</td>
                  <td>caca</td>
                  <td><a href="" class="btn btn-warning">Edit</a> <a href="" class="btn btn-danger">Delete</a></td>
              </tr>
          </table>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/tanaman-create.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $e)
                        <li>{{$e}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{ route('admin.tanaman.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Enter name">
                </div>
                <div class="form-group">
                    <label for="jenis">Jenis</label>
                    <input type="text" class="form-control" id="jenis" placeholder="jenis" name="jenis">
                </div>
                <div class="form-group">
                    <label for="desc">Desc</label>
                    <input type="text" class="form-control" id="desc" name ="desc"  placeholder="desc">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="image" name="image">
                            <label class="custom-file-label" for="image">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="link">Link</label>
                    <input type="text" class="form-control" id="link" name ="link"  placeholder="link">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/tanaman-edit.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        {{ $module_name }}
        <small>{{ $submodule_name }}</small>
        </h1>
      <ol class="breadcrumb">
        <li>{{ $module_name }}</li>
        <li class="active">{{ $submodule_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Tambah Data</h3>
        </div>
        <div class="box-body">
            <form action="{{ route('admin.tanaman.update', ['tanaman'=>$tanaman->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Enter name" value="{{$tanaman->name}}">
                </div>
                <div class="form-group">
                    <label for="jenis">Jenis</label>
                    <input type="text" class="form-control" id="jenis" placeholder="jenis" name="jenis" value="{{$tanaman->jenis}}">
                </div>
                <div class="form-group">
                    <label for="desc">Desc</label>
                    <input type="text" class="form-control" id="desc" name ="desc"  placeholder="desc" value="{{$tanaman->desc}}">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="exampleInputFile" name="image">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                        <img src="{{asset($tanaman->image)}}" alt="image" height="250px">
                    </div>
                </div>
                <div class="form-group">
                    <label for="link">Link</label>
                    <input type="text" class="form-control" id="link" name ="link"  placeholder="link" value="{{$tanaman->link}}">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/tanaman-index.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ $module_name }}
      </h1>
      <ol class="breadcrumb">
        <li class="active">{{ $module_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"></h3>
          <a href="{{ route('admin.tanaman.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="box-body">
          <table class="table">
              <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Jenis</th>
                  <th>Desc</th>
                  <th>Image</th>
                  <th>Link</th>
                  <th>Action</th>
              </tr>
              @foreach($tanamans as $item)
              <tr>
                <td>{{$item->id}}</td>
                <td>{{$item->name}}</td>
                <td>{{$item->jenis}}</td>
                <td>{{$item->desc}}</td>
                <td><img src="{{asset($item->image)}}" alt="image" height="250px"></td>
                <td>{{$item->link}}</td>
                  <td><a href="{{route('admin.tanaman.edit', ['tanaman'=>$item->id])}}" class="btn btn-warning">Edit</a> <a class="btn btn-danger" onclick="event.preventDefault();$('#tanamanDelete').submit()">Delete</a></td>
                  <form id="tanamanDelete" action="{{ route('admin.tanaman.destroy', ['tanaman'=>$item->id]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                  </form>
              </tr>
              @endforeach
          </table>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

laravel/resources/views/admin/user-index.blade.php
@extends('admin.layout.app')
@section('header')
    @include('admin.layout.header')
@endsection
@section('leftbar')
    @include('admin.layout.leftbar')
@endsection
@section('rightbar')
    @include('admin.layout.rightbar')
@endsection
@section('content')
 <!-- Content Wrapper. Contains page content -->
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ $module_name }}
      </h1>
      <ol class="breadcrumb">
        <li class="active">{{ $module_name }}</li>
      </ol>
    </section>

    <section class="content">
    <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"></h3>
          <a href="{{ route('admin.user.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="box-body">
          <table class="table">
              <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Password</th>
                  <th>Is_Admin</th>
                  <th>Action</th>
              </tr>
              <tr>
                  <td>1</td>
                  <td>Caca</td>
                  <td>caca</td>
                  <td><a href="" class="btn btn-warning">Edit</a> <a href="" class="btn btn-danger">Delete</a></td>
              </tr>
          </table>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection